services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    restart: always
    env_file:
      - ../.env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    restart: always
    env_file:
      - ../.env
    secrets:
      - db_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:

  mariadb_data:
    driver: local

  wordpress_data:
    driver: local

networks:

  inception:
    driver: bridge

secrets:

  db_password:
    file: ../secrets/db_password.txt

  db_root_password:
    file: ../secrets/db_root_password.txt